spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring-security-db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: idiot_Yuqn@123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
